---
# This playbook install the apps required in a server

- name: install splunk binary
  tags:
   - install
  apt: deb=/var/tmp/splunk/{{splunk_binary}} 


- name: accept license
  tags:
   - install
  shell: /opt/splunk/bin/splunk start --accept-license 

- name: enable init script
  tags:
   - install
  shell: /opt/splunk/bin/splunk enable boot-start 
