---
# This playbook deploys all sub playbooks

- name: apply common configuration to all nodes
  hosts: universal_forwarder
  user: root
  vars:
    # splunk universal forwarder binary to install
    splunk_uf_binary: 'splunkforwarder-6.2.0-237341-Linux-x86_64.tgz'

  roles:
    - common
    - universal_forwarder


